name: BookApp

on:
  push:
    branches:
      - develop
      - main

jobs:
  CI_CD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/unit

      - name: Create archive of dependencies
        run: |
          source venv/bin/activate
          cd .aws-sam/build/BookApp/
          zip -r api.zip ./
          mv api.zip $GITHUB_WORKSPACE

      - name: Upload ZIP file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: ${{ github.workspace }}/api.zip

  CD:
    runs-on: ubuntu-latest
    needs: CI_CD
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Download Lambda artifact
        uses: actions/download-artifact@v2
        with:
          name: api

      - name: Upload to S3
        run: aws s3 cp api.zip s3://bookappfast/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Update Lambda function
        run: aws lambda update-function-code --function-name book_app --s3-bucket bookappfast --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
